language: python
python:
  - "3.5"
jdk:
  - oraclejdk8
node_js:
  - "4.2.6"
cache: pip
before_install:
  - mkdir /tmp/bin
  - export PATH=$PATH:/tmp/bin
install:
  - curl --location 'https://www.ortussolutions.com/parent/download/commandbox/type/bin' -o /tmp/box.zip
  - unzip /tmp/box.zip -d /tmp/bin
  - pip install awscli
script: ./buildDeployAndPublish.sh

notifications:
  email: false